FROM debezium/connect:2.7.0.Final

# Install MSK IAM auth plugin on main classpath (required for SASL callbacks)
RUN cd /kafka/libs && \
    curl -sLO https://github.com/aws/aws-msk-iam-auth/releases/download/v2.0.3/aws-msk-iam-auth-2.0.3-all.jar

# Install Confluent Avro converter + all transitive dependencies on classpath
RUN cd /kafka/libs && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.6.1/kafka-connect-avro-converter-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-data/7.6.1/kafka-connect-avro-data-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.6.1/kafka-avro-serializer-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.6.1/kafka-schema-serializer-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/7.6.1/kafka-schema-converter-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.6.1/kafka-schema-registry-client-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/common-config/7.6.1/common-config-7.6.1.jar && \
    curl -sLO https://packages.confluent.io/maven/io/confluent/common-utils/7.6.1/common-utils-7.6.1.jar && \
    curl -sLO https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar && \
    curl -sLO https://repo1.maven.org/maven2/com/google/guava/guava/32.1.3-jre/guava-32.1.3-jre.jar && \
    curl -sLO https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.2/failureaccess-1.0.2.jar
